### ISSUE TITLE
Tracking: Plasma Mode Generic Commitments

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/optimism#10400]
Tickets to Complete
- [x] https://github.com/ethereum-optimism/optimism/issues/10312
- [x] https://github.com/ethereum-optimism/optimism/issues/10399
- [x] #10453
- [x] https://github.com/ethereum-optimism/optimism/issues/10401
- [x] https://github.com/ethereum-optimism/optimism/issues/10402
- [x] #10472
