### ISSUE TITLE
Governance: Advanced Delegation Tracking

### ISSUE THREAD

**Issue by 0xfuturistic** [ethereum-optimism/optimism#10849]
# Tracking of Scope

Objective: create and integrate `GovernanceDelegation` with the `GovernanceToken` for advanced delegation.

- [x] `GovernanceToken`: design doc -> https://github.com/ethereum-optimism/design-docs/blob/main/governance/advanced-delegation.md
- [x] `GovernanceToken`: specs -> https://github.com/ethereum-optimism/specs/blob/main/specs/governance/gov-token.md
- [x] `GovernanceToken`: implementation update -> https://github.com/ethereum-optimism/optimism/pull/11167/
- [x] `GovernanceDelegation`: specs -> https://github.com/ethereum-optimism/specs/pull/247
- [ ] `GovernanceDelegation`: implementation -> https://github.com/ethereum-optimism/optimism/pull/11167/
