### ISSUE TITLE
Interop: op-supervisor tracker

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#10856]
Tracking issue for the work required to get op-supervisor to a minimum viable implementation.

## Required For E2E Tests + Devnet 1
* [x]  ethereum-optimism/optimism#10857 
* [x] https://github.com/ethereum-optimism/optimism/issues/10999
* [x] https://github.com/ethereum-optimism/optimism/issues/11023
* [x] https://github.com/ethereum-optimism/optimism/issues/11024
* [x] https://github.com/ethereum-optimism/optimism/issues/11028
* [x] https://github.com/ethereum-optimism/optimism/issues/11029
* [x] https://github.com/ethereum-optimism/optimism/issues/11031
* [x] https://github.com/ethereum-optimism/optimism/issues/11030
* [x] https://github.com/ethereum-optimism/optimism/issues/11308

## Required For DevNet 2
* [x] https://github.com/ethereum-optimism/optimism/issues/11044
* [x] https://github.com/ethereum-optimism/optimism/issues/11026
* [x] https://github.com/ethereum-optimism/optimism/issues/11027
* [x] https://github.com/ethereum-optimism/optimism/issues/11091

## Post-Devnet
* [x] https://github.com/ethereum-optimism/optimism/issues/11032
* [x] https://github.com/ethereum-optimism/optimism/issues/11105

**Comment by protolambda** [comment]
Everything currently in the tracker is either done or stale. Reorg-handling is tracked in new smaller tickets. And we use milestones instead of trackers now. Closing this.
