### ISSUE TITLE
GovToken: Partial Delegation Tracking

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#10861]
# Tracking ticket for Partial Delegation

This ticket is tracking the set of work that involves completing an implementation of GovToken with Partial Delegation

- [x] https://github.com/ethereum-optimism/protocol-quest/issues/277
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/278
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/280
- [x] https://github.com/ethereum-optimism/optimism/issues/10863
- [x] https://github.com/ethereum-optimism/optimism/issues/10862
