### ISSUE TITLE
Driver: Incremental OnEvent adoption

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#10865]
Change the `Driver` of the op-node to structure the deriver sub-processes with event-processing, as described in phase 2 of the design doc: https://github.com/ethereum-optimism/design-docs/blob/main/protocol/op-node-derivers.md#2-incremental-onevent-adoption

- [x] ethereum-optimism/optimism#10854
- [x] ethereum-optimism/optimism#10853
- [x] #10957
- [x] #10958
- [x] #10959
- [x] #10969
- [x] ethereum-optimism/optimism#10852
- [x] ethereum-optimism/optimism#10851
- [x] #10979
- [x] ethereum-optimism/optimism#10850
- [x] #11002
- [x] https://github.com/ethereum-optimism/optimism/issues/10983
- [x] #11097
- [x] #11098

**Comment by protolambda** [comment]
Tracking polishing separately now, this is done
