### ISSUE TITLE
Interop: Standalone service, with disk append-log and non-recursive resolution.

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#10860]
- [x] ethereum-optimism/optimism#10859
- [x] ethereum-optimism/optimism#10856
- [x] ethereum-optimism/optimism#10857
- [x] ethereum-optimism/optimism#10855
- [x] ethereum-optimism/optimism#10858
- [x] ethereum-optimism/optimism#10847

**Comment by protolambda** [comment]
We have too many conflicting op-supervisor tracking issues. The MVP issue https://github.com/ethereum-optimism/optimism/issues/10856 captures a good summary. Closing this.
