### ISSUE TITLE
Interop: Devnet Infra Tracker

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#10866]
This is a high level tracking ticket for setting up the infrastructure to operate an interop devnet.

The interop devnet will consist of 2 L2 chains that are deployed to Sepolia. They will both depend on each other.

This ticket can be considered done when the devnet is operating. The sequencer RPC does not need to be public for this to be complete but devs at OP Labs or other collaborating teams will need to be able to access it.

- [x] https://github.com/ethereum-optimism/optimism/issues/10895
  - [x] https://github.com/ethereum-optimism/optimism/issues/10881
    - [x] https://github.com/ethereum-optimism/optimism/issues/10880

**Comment by protolambda** [comment]
Working towards stable devnet milestone now, closing this.
