### ISSUE TITLE
Interop: SuperchainERC20 Tracking

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#10877]
This is a tracking issue for the `SuperchainERC20` feature. The goal of `SuperchainERC20` is to be an application on top of the native interoperability protocol that enables fungible and portable ERC20 tokens across the superchain. This requires a public spec with public feedback to ensure that we are building something useful for builders on the superchain

- [x] https://github.com/ethereum-optimism/optimism/issues/10876
- [x] https://github.com/ethereum-optimism/optimism/issues/10875
  - [x] https://github.com/ethereum-optimism/optimism/issues/10874
- [x] https://github.com/ethereum-optimism/optimism/issues/10873
- [x] https://github.com/ethereum-optimism/optimism/issues/10872

**Comment by protolambda** [comment]
All checklist items are done, and the issue hasn't been updated for many months, so I am closing this.
