### ISSUE TITLE
Tracking: Custom Gas Token

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#10879]
Top level tracking ticket for custom gas token work.

**Launch Target: April 29th**

- [x] https://github.com/ethereum-optimism/protocol-quest/issues/215
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/216
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/217
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/218
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/222
- [ ] https://github.com/wevm/viem/discussions/2197
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/244
- [x] https://github.com/ethereum-optimism/optimism/issues/10871
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/251

**Comment by tynes** [comment]
Closing this
