### ISSUE TITLE
Interop: devnet v1 protocol predeploys tracker

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#10889]
# Overview

This is a tracking ticket for all smart contract related work for the interop devnet release.

## Definition of Done

This ticket can be considered done when each implementation has been implemented per the spec with sufficient test coverage and it is possible to use a single config option when doing L1 contract deployments and L2 genesis generation to create an interop ready network.

Open issues:

`L1Block`
- [x] ethereum-optimism/protocol-quest#168
- [x] ethereum-optimism/protocol-quest#169
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/242
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/264

`OptimismPortal`
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/265

`L2ToL2CrossChainMessenger`:
- [x] ethereum-optimism/protocol-quest#162
- [x] ethereum-optimism/protocol-quest#163

`CrossL2Inbox`:
- [x] ethereum-optimism/protocol-quest#165
- [x] ethereum-optimism/protocol-quest#167 

`SystemConfig`:
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/243 

`L2 Genesis`:
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/247
- [x] ethereum-optimism/protocol-quest#166 
- [x] ethereum-optimism/protocol-quest#164

Old issues:
- [x] ethereum-optimism/protocol-quest#152
- [x] ethereum-optimism/protocol-quest#133 
- [x] Fix stack too deep issue with Foundary (context: https://github.com/ethereum-optimism/client-pod/issues/686 )
- [x] Fix foundry-compiler issues with new version
- [x] ethereum-optimism/protocol-quest#170

Predeploys implementation (excl. tests):
- [x] ethereum-optimism/protocol-quest#175

**Comment by tynes** [comment]
The predeploys are nearly done. The only thing left that needs to be handled for the devnet release is https://github.com/ethereum-optimism/design-docs/pull/13

**Comment by tynes** [comment]
Closing this as complete
