### ISSUE TITLE
Interop: Go e2e tracker

### ISSUE THREAD

**Issue by hamdiallam** [ethereum-optimism/optimism#10896]
Superchain backend:
- [x] ethereum-optimism/optimism#10869
  - [x] ethereum-optimism/optimism#10860
    - [x] ethereum-optimism/optimism#10859
    - [x] ethereum-optimism/optimism#10856
    - [x] ethereum-optimism/optimism#10857
    - [x] ethereum-optimism/optimism#10855
    - [x] ethereum-optimism/optimism#10858
- [x] ethereum-optimism/optimism#10883 

Geth:
- [x] ethereum-optimism/optimism#10891
- [x] https://github.com/ethereum-optimism/optimism/issues/10867

Driver / derivation:
- [ ] https://github.com/ethereum-optimism/specs/pull/96
- [x] ethereum-optimism/protocol-quest#192
- [x] ethereum-optimism/optimism#10888
  - [x] https://github.com/ethereum-optimism/protocol-quest/issues/260
    - [x] ethereum-optimism/protocol-quest#262
    - [x] ethereum-optimism/protocol-quest#270
    - [x] ethereum-optimism/protocol-quest#271
    - [x] ethereum-optimism/protocol-quest#272
  - [x] ethereum-optimism/protocol-quest#261
  - [ ] ethereum-optimism/optimism#10865  (see sub-tracking issue)
  - [x] ethereum-optimism/optimism#10864
- [x] ethereum-optimism/optimism#10887 

- [x] ethereum-optimism/optimism#10884
- [x] ethereum-optimism/optimism#10885
- [x] https://github.com/ethereum-optimism/protocol-quest/issues/226

Testing:
- [ ] Low Latency E2E Test
