### ISSUE TITLE
Governance: Interoperability Tracking

### ISSUE THREAD

**Issue by cairoeth** [ethereum-optimism/optimism#11206]
# Tracking of Scope

Objective: make the `GovernanceToken` with `GovernanceDelegation` be interoperable

- [] [`GovernanceDelegation`: interop design doc](https://github.com/ethereum-optimism/optimism/issues/11207)
- [] [`Governor`: interop design doc](https://github.com/ethereum-optimism/optimism/issues/11307)
- [] [`Governance`: interop implementation](https://github.com/ethereum-optimism/optimism/issues/11208)
