### ISSUE TITLE
op-chain-ops: Forge scripts in Go [tracker]

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#11490]
- [x] https://github.com/ethereum-optimism/op-geth/pull/359
- [x] #11443
- [x] #11444
- [x] #11445
- [x] #11446
- [x] https://github.com/ethereum-optimism/optimism/pull/11447
- [x] https://github.com/ethereum-optimism/optimism/pull/11465
- [x] #11491
- [x] https://github.com/ethereum-optimism/optimism/pull/11577

See design-doc for context: 

The TLDR:
- we are getting rid of pre-configured allocs (too monolithic / inflexible)
- we are running forge scripts in Go to generate state (during test, can fully cutomize deployment calls!)

This unblocks interop op-e2e tests / local devnet, by making incremental deploy steps onto the same state.

In parallel to this work there is the OPSM 0.5 milestone, which refactors the input/output system of deploy/genesis scripts, and makes them more modular. This then will allow us to compose a deployment (e.g. 1 L1 dev chain, 1 superchain, multiple L2 deployments, and interop extensions applied to each L2 genesis).
