### ISSUE TITLE
Implement offchain MT FPVM 

### ISSUE THREAD

**Issue by Inphi** [ethereum-optimism/optimism#11642]
Provide an offchain implementation of the [MT FPVM spec](https://github.com/ethereum-optimism/optimism/issues/11644).

Assuming all development is done on develop, this should be done as a new VM implementation, rather than replace the current one. We'll still need the old one around until the MT FPVM is deployed to mainnet. 

TODOs:
- [x] Update cannon commands so we are able to run mtCannon through the CLI
- [ ] Add more testing
  - [x] ethereum-optimism/optimism#11659
  - [x] ethereum-optimism/optimism#11658
  - [x] ethereum-optimism/optimism#11657
  - [x] ethereum-optimism/optimism#11656
  - [x] ethereum-optimism/optimism#11655
- [ ] Finalize patching approach for mtCannon.  
  - [x] ethereum-optimism/optimism#11654
  - [ ] Decide on an approach for disabling memory profiling in go programs
    - See this [comment](https://github.com/ethereum-optimism/optimism/pull/11188#discussion_r1692011483) and [this commit](https://github.com/ethereum-optimism/optimism/pull/11188/commits/4fd9c3917baf9c17d1642576d73eea53616cc440).
    - Created a separate issue for this: https://github.com/ethereum-optimism/optimism/issues/11660

**Comment by Inphi** [comment]
https://github.com/ethereum-optimism/optimism/issues/11637 paritally implements this ticket.

**Comment by Inphi** [comment]
Closing this as the VMs are implemented. Additional tasks are created for testing in other issues.
