### ISSUE TITLE
Interop: devnet UX checklist

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#11774]
Checklist of minor things to improve before public devnet 1:
- [x] The `supervisor` CLI flag on op-node is hidden (it's experimental, not encouraged to use, yet). We may want to unhide this flag for public usage later.
- [x] Add op-supervisor metrics
- [x] Improve op-supervisor logging
