### ISSUE TITLE
MTCannon: Increase differential test coverage across opcodes

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/optimism#12032]
## Description

Increase differential test coverage across MIPS opcodes.  We have some basic coverage with the [existing open mips tests](https://github.com/ethereum-optimism/optimism/blob/bd50ac6909245e6a283e824995940fc055a90f14/cannon/mipsevm/tests/evm_common_test.go#L24-L24), but we should try to get more coverage around edge cases.  Look into adding more tests and porting existing tests from [MIPS.t.sol.](https://github.com/ethereum-optimism/optimism/blob/2f2554af50f88840d5ff6f38ba967737878cd933/packages/contracts-bedrock/test/cannon/MIPS.t.sol)  

New tests should follow the single-step unit test pattern as in [this example](https://github.com/ethereum-optimism/optimism/blob/bd50ac6909245e6a283e824995940fc055a90f14/cannon/mipsevm/tests/evm_common_test.go#L165-L228), rather than adding more assembly tests.  The list of supported instructions is available [in the README](https://github.com/ethereum-optimism/optimism/blob/develop/cannon/mipsevm/README.md).  Documentation on MIPS instructions can be found [here](https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf).

**Comment by GrapeBaBa** [comment]
@mbaxter I see a series of issues related to cannon testing. Are these issues already in development, and are they suitable for external contributors like us to contribute?

**Comment by mbaxter** [comment]
@GrapeBaBa - no one is assigned to this yet, so happy to have external contributors take a look!  Let me know if you have any questions.

**Comment by Inphi** [comment]
@GrapeBaBa would you be able to take on this issue?

**Comment by GrapeBaBa** [comment]
> @GrapeBaBa would you be able to take on this issue?

Yes

**Comment by GrapeBaBa** [comment]
- [x] [add/addi/addu/addiu test](https://github.com/ethereum-optimism/optimism/issues/12084)
- [x] [sub/subu/and/andi/or/ori/xor/xori/nor/slt/sltu tests](https://github.com/ethereum-optimism/optimism/issues/12103)
- [x] [lb/lh/lw/lbu/lhu/lwl/lwr/sb/sh/swl/sw/swr tests](https://github.com/ethereum-optimism/optimism/issues/12195)
- [x] [movz/movn tests](https://github.com/ethereum-optimism/optimism/issues/12351)
- [x] [movf/movt tests](https://github.com/ethereum-optimism/optimism/issues/12391)
- [x] [mul/div opcodes tests](https://github.com/ethereum-optimism/optimism/issues/12458)

**Comment by Inphi** [comment]
Looks like this is done. Thanks!

**Comment by GrapeBaBa** [comment]
> Looks like this is done. Thanks!

@Inphi I think it is still a lot of tests need to port, I plan to use this task tracking all the sub tasks, can you reopen it?

**Comment by Inphi** [comment]
Ah right. Sorry about that.

**Comment by mbaxter** [comment]
@GrapeBaBa - just noticed that the new [LoadStore tests](https://github.com/ethereum-optimism/optimism/blob/82c9b12db884cb712394db837e1fb9ec118a4375/cannon/mipsevm/tests/evm_common_test.go#L245-L316) fell through the cracks wrt the [64-bit refactor](https://github.com/ethereum-optimism/optimism/pull/12029).  Would you mind updating these to use the new [`Word` architecture-specific variables](https://github.com/ethereum-optimism/optimism/blob/82c9b12db884cb712394db837e1fb9ec118a4375/cannon/mipsevm/tests/evm_common_test.go#L173-L174)?

**Comment by GrapeBaBa** [comment]
> @GrapeBaBa - just noticed that the new [LoadStore tests](https://github.com/ethereum-optimism/optimism/blob/82c9b12db884cb712394db837e1fb9ec118a4375/cannon/mipsevm/tests/evm_common_test.go#L245-L316) fell through the cracks wrt the [64-bit refactor](https://github.com/ethereum-optimism/optimism/pull/12029). Would you mind updating these to use the new [`Word` architecture-specific variables](https://github.com/ethereum-optimism/optimism/blob/82c9b12db884cb712394db837e1fb9ec118a4375/cannon/mipsevm/tests/evm_common_test.go#L173-L174)?

Ok, will do it.

**Comment by Inphi** [comment]
@GrapeBaBa Are we good to close out this ticket?

**Comment by GrapeBaBa** [comment]
There are still a few tests that need to be migrated. If it's not necessary, I suggest not closing it for now.

**Comment by Inphi** [comment]
Gotcha. Let's keep this issue open then. The remaining instruction tests to be migrated are:

- [ ] - jalr
- [ ] - lui
- [ ] - srav
- [ ] - sll
- [ ] - srl
- [ ] - clz
- [ ] - clo
- [ ] - srlv
- [ ] - bgtz
- [ ] - bne
- [ ] - beq
- [ ] - jump

Feel free to create sub-issues for these as needed.

**Comment by BlocksOnAChain** [comment]
@GrapeBaBa  - hey, wanted to check about your plans to continue work on this issue, since it would be great to close the remaining work?

**Comment by GrapeBaBa** [comment]
should be finished this weekend
