### ISSUE TITLE
tracking: MT-Cannon: Complete 64-bit Go VM

### ISSUE THREAD

**Issue by Inphi** [ethereum-optimism/optimism#12205]
Following up on https://github.com/ethereum-optimism/optimism/pull/12029/files, resolve the TODOs in that PR and wrap up the 64-bit VM.

This is done in two phases. First we complete the 64-bit multithreaded Cannon VM in Go. The target milestone is to be able to generate a trace for a Go program compiled to Linux/MIPS64. After that, we'll implement a new FPVM in solidity that implements 64-bit MT-Cannon. This issue tracks the first phase.

- [x] #12241
- [x] #12242
- [x] #12243
- [x] #12244
- [x] #12245
- [x] #12246
- [x] #12248
- [x] #12249
- [x] #12247
- [x] #12252

**Comment by Inphi** [comment]
- [ ] 64-bit Program Loading
- [ ] ll/sc and lld/scd 64-bit emulation
- [ ] 64-bit arithmetic instructions
- [ ] Fix memory.go for the 64-bit VM
- [ ] Emulate syscalls for Linux/MIPS64
- [ ] Introduce MIPS64 assembly test vectors
- [ ] Improve test coverage of the MIPS64 state codec
- [ ] Add new 64-bit instructions to STF tests
- [ ] Add 64-bit Go programs to STF tests
- [ ] Replace 32-bit MT-Cannon tests with the 64-bit VM in CI
