### ISSUE TITLE
interop: op-supervisor stability tracker

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#12423]
- [x] op-supervisor should track a more reliably defined set of chains.
- [x] op-supervisor should warn (logs and metrics) when there is no signal for a given chain in a while.
- [x] deduplicate background-processing startup between `SupervisorBackend.Start` and `NewSupervisorBackend` constructor.

**Comment by axelKingsley** [comment]
I think this task needs to be reviewed, as it potentially isn't accurate to supervisor behavior anymore. The supervisor tracks the dependency set, and warns when the there is no Managed Node to do L1 derivation against.

**Comment by protolambda** [comment]
Stale, closing.
