### ISSUE TITLE
Holocene-D: Pipeline improvements tracker

### ISSUE THREAD

**Issue by sebastianst** [ethereum-optimism/optimism#12490]
Tracking (non-blocking) observations and todos from https://github.com/ethereum-optimism/optimism/pull/12506

- [ ] Garbage collect left-over state in state multiplexers?
- [ ] Refactor `Reset` to be called recursively on previous stages? So going from a _horizontal_ model, where the pipeline iterates over the stages and `Reset`s each, to a _vertical_ model where each stage owns the previous and resets it. There's only a single Reset that actually makes a network call (`L1Retrieval.Reset`), while all other resets simply clear some fields and slices, so there's no real value in _stepping_ through each reset individually. Note that this is actually more consistent to how each stage also fetches data from the previous stage (`prev.NextData` etc) - it is not fetched by the pipeline on each stage and then passed on to the next stage. I also choose to make `FlushChannel` work with this vertical ownership model as well. (And the Rust implementation of the DP also works with the same model.)
- [ ] Clarify if the `DepositsOnlyPayloadAttributesRequest` case in `EngDeriver.onPayloadProcess` can actually happen. To the best of my understanding the FCU call should already fail before during derivation.

See also https://github.com/ethereum-optimism/optimism/issues/12444

**Comment by protolambda** [comment]
Can this be closed?

**Comment by sebastianst** [comment]
Moved the modular fork handling notes into its own issue https://github.com/ethereum-optimism/optimism/issues/14756

**Comment by sebastianst** [comment]
In view of https://github.com/ethereum-optimism/design-docs/pull/213 we can close this issue for now.

**Comment by ajsutton** [comment]
Reopening as we still have 4 todos in the code for this issue:
```
ethereum-optimism/optimism #12490        | Holocene-D: Pipeline improvements tracker                         | op-node/rollup/types_test.go:779                  
ethereum-optimism/optimism #12490        | Holocene-D: Pipeline improvements tracker                         | op-node/rollup/types.go:511                       
ethereum-optimism/optimism #12490        | Holocene-D: Pipeline improvements tracker                         | op-node/rollup/derive/batch_mux.go:35             
ethereum-optimism/optimism #12490        | Holocene-D: Pipeline improvements tracker                         | op-node/rollup/derive/channel_mux.go:39           
```

Seems like those todos could potentially just be removed.

**Comment by sebastianst** [comment]
op-node will be deprecated, so closing as not planned
