### ISSUE TITLE
[Tracker] Isthmus Upgrade

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#12703]
This is out of date

General tracking for features proposed to be included in the Isthmus upgrade.

## Pre-requisite

- [x] #13069 

### Smart contract work

- [ ] #11527
    - [ ] [Implementation](https://github.com/ethereum-optimism/optimism/pull/12356)
    - [x] [PR: make Cannon libraries version agnostic](https://github.com/ethereum-optimism/optimism/pull/13175)
- [ ] #11558 
- [ ] #12478 
    - [ ] [Design Doc](https://github.com/ethereum-optimism/design-docs/pull/143)
    - [ ] [Implementation]()
- [ ] #13058 
    - [x] [PR: import statement cleanup](https://github.com/ethereum-optimism/optimism/pull/13056)
    - [x] [PR: move interfaces to new top-level folder](https://github.com/ethereum-optimism/optimism/pull/13114)
- [x] #11093 
    - [x] [PR: fix stack too deep error in PermissionedDisputeGame](https://github.com/ethereum-optimism/optimism/pull/13141)
    - [x] [PR: fix stack too deep error in MIPS](https://github.com/ethereum-optimism/optimism/pull/13137)
    - [x] [PR: fix stack too deep in LibKeccak](https://github.com/ethereum-optimism/optimism/pull/13136)
- [ ]  #12172
- [ ] Include Custom Gas Token code

### Other features

- [x] #12044 
  - [x] [PR op-geth: Isthmus: Tests and misc updates for L2 withdrawals root](https://github.com/ethereum-optimism/op-geth/pull/399) 
  - [x] [PR op-geth: Isthmus: withdrawals root in block header](https://github.com/ethereum-optimism/op-geth/pull/451)
  - [x] [PR: Config: Add support for Isthmus](https://github.com/ethereum-optimism/optimism/pull/12847)
  - [x] [PR: Updates for withdrawals root in block header](https://github.com/ethereum-optimism/optimism/pull/13962)
  - [x] [PR: op-program use withdrawalRoot from header if Isthmus](https://github.com/ethereum-optimism/optimism/pull/14180)
  - [ ] [PR: Action Tests](https://github.com/ethereum-optimism/optimism/pull/12925)
- [x] [Operator Fee](https://github.com/ethereum-optimism/specs/pull/382)
    - [ ] [Design Doc](https://github.com/ethereum-optimism/design-docs/pull/81/files)
- [ ] [Header Accumulator](https://github.com/ethereum-optimism/specs/pull/259)
- [x] https://github.com/ethereum-optimism/specs/issues/511

## Probably NGMI this time

- [x] #12435
- [ ] [Deposit Queue](https://github.com/ethereum-optimism/specs/pull/82)
- [ ] [Decouple block times between L1 and L2 (or L2 and L3)](https://github.com/ethereum-optimism/specs/issues/416)

---
NB - the above is all subject to further discussion and agreement; nothing is set in stone just yet. But we are no longer taking further submissions for Isthmus (unless they are extraordinarily important).

**Comment by emhane** [comment]
op-reth tracking issue https://github.com/paradigmxyz/reth/issues/13145

**Comment by mdehoog** [comment]
~Hey 👋  what do we think of including the consensus nonce change (as an alternative to the deposit queue)? I've created a tracking issue here: https://github.com/ethereum-optimism/optimism/issues/13543, hoping to have it code complete early next week.~

Moved to Jovian

**Comment by emhane** [comment]
could you please strike through withdrawals root list to reflect the decision made in yesterdays meeting to exclude it from isthmus. same with operator fee @smartcontracts

**Comment by Yn2o** [comment]
👏 Great work on the smart contract updates! For the Solidity upgrade (0.8.15 → 0.8.25), were regression tests performed to ensure compatibility

**Comment by bentrnr21** [comment]
Regarding the Isthmus upgrade, do you already have a list of major changes planned? I’d be interested in testing specific areas or providing feedback on certain functionalities. Let me know if there are particular areas where help is needed.

**Comment by Dustin4444** [comment]
> General tracking for features proposed to be included in the Isthmus upgrade.
> 
> ## Pre-requisite
> * [ ]  [[Tracker] OPCM Upgrades (Upgrade 13) #13069](https://github.com/ethereum-optimism/optimism/issues/13069)
> 
> ## Isthmus Candidates
> ### Smart contract work
> * * [ ]  [EVM Engineering: Update all `0.8.15` code to `0.8.25` #11527](https://github.com/ethereum-optimism/optimism/issues/11527)
>     
>     * [ ]  [Implementation](https://github.com/ethereum-optimism/optimism/pull/12356)* [x]  [PR: make Cannon libraries version agnostic](https://github.com/ethereum-optimism/optimism/pull/13175)[ ]  [L2 Genesis Simplification #11558](https://github.com/ethereum-optimism/optimism/issues/11558)* [ ]  [EVM Engineering: Standardize a custom error convention #12478](https://github.com/ethereum-optimism/optimism/issues/12478)
>     
>     * [ ]  [Design Doc](https://github.com/ethereum-optimism/design-docs/pull/143)* [ ]  Implementation* [ ]  [EVM Engineering: stylistic cleanup #13058](https://github.com/ethereum-optimism/optimism/issues/13058)
>     
>     * [x]  [PR: import statement cleanup](https://github.com/ethereum-optimism/optimism/pull/13056)* [x]  [PR: move interfaces to new top-level folder](https://github.com/ethereum-optimism/optimism/pull/13114)* [x]  [[Tracker] EVM Engineering: solidity code coverage #11093](https://github.com/ethereum-optimism/optimism/issues/11093)
>     
>     * [x]  [PR: fix stack too deep error in PermissionedDisputeGame](https://github.com/ethereum-optimism/optimism/pull/13141)* [x]  [PR: fix stack too deep error in MIPS](https://github.com/ethereum-optimism/optimism/pull/13137)* [x]  [PR: fix stack too deep in LibKeccak](https://github.com/ethereum-optimism/optimism/pull/13136)[ ]   [[Tracker] Proofs: Incident Response Improvements (Upgrade 13) #12172](https://github.com/ethereum-optimism/optimism/issues/12172)[ ]  Include Custom Gas Token code
> 
> ### Other features
> * * [x]  [[Tracker] L2 withdrawals-root in block header (Isthmus) #12044](https://github.com/ethereum-optimism/optimism/issues/12044)
>     
>     * [x]  [PR op-geth: Isthmus: Tests and misc updates for L2 withdrawals root](https://github.com/ethereum-optimism/op-geth/pull/399)* [x]  [PR op-geth: Isthmus: withdrawals root in block header](https://github.com/ethereum-optimism/op-geth/pull/451)* [x]  [PR: Config: Add support for Isthmus](https://github.com/ethereum-optimism/optimism/pull/12847)* [x]  [PR: Updates for withdrawals root in block header](https://github.com/ethereum-optimism/optimism/pull/13962)* [x]  [PR: op-program use withdrawalRoot from header if Isthmus](https://github.com/ethereum-optimism/optimism/pull/14180)* [ ]  [PR: Action Tests](https://github.com/ethereum-optimism/optimism/pull/12925)* [x]  [Operator Fee](https://github.com/ethereum-optimism/specs/pull/382)
>     
>     * [ ]  [Design Doc](https://github.com/ethereum-optimism/design-docs/pull/81/files)[ ]  [Header Accumulator](https://github.com/ethereum-optimism/specs/pull/259)[x]  [EIP-7702: Set EOA account code specs#511](https://github.com/ethereum-optimism/specs/issues/511)
> 
> ## Probably NGMI this time
> * [ ]  [[Tracker] OP Stack: Support Pectra (Isthmus) #12435](https://github.com/ethereum-optimism/optimism/issues/12435)[ ]  [Deposit Queue](https://github.com/ethereum-optimism/specs/pull/82)[ ]  [Decouple block times between L1 and L2 (or L2 and L3)](https://github.com/ethereum-optimism/specs/issues/416)
> 
> NB - the above is all subject to further discussion and agreement; nothing is set in stone just yet. But we are no longer taking further submissions for Isthmus (unless they are extraordinarily important).

**Comment by sebastianst** [comment]
Isthmus is done
