### ISSUE TITLE
[Tracker] OPCM Upgrades (Upgrade 13)

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimism#13069]
## Description

This is a tracking issue for the work outlined in the [L1 Upgrades Design Doc](https://github.com/ethereum-optimism/design-docs/blob/main/protocol/l1-upgrades.md).

## Milestone: Devnet

Items which must be completed prior to the devnet deployment.

- [x] #13079 
- [x] #13339
- [x] #13073
- [x] #13589
- [x] #13076
- [x] #13072
- [x] #13071  
- [x] #13671
- [x] #13682

## Milestone: Betanet (Feb 4)

- [x] #13362
- [x] https://github.com/ethereum-optimism/optimism/issues/14815

## Milestone: Testnet (Feb 20)

Items which must be completed prior to the testnet deployment.

- [x] #13078
- [x] #13644
- [x] #13401
- [x] #13593
- [x] #13077
- [x] #13070
- [x] #13388
- [x] #13836
- [x] #13993
- [x] #13996
- [x] #13411
- [x] #13081
- [x] #14140
- [x] #14141 
- [x] #14142
- [x] #14173
- [x] #13835
- [ ] #13607
- [ ] https://github.com/ethereum-optimism/design-docs/issues/200
- [ ] #13080

## Milestone: Governance Proposal (Feb 27)

- [x] Post Proposal

## Milestone: Mainnet (April 2)

Items which must be completed prior to the mainnet deployment.

- [x] #13082
- [ ] #13380
- [x] https://github.com/ethereum-optimism/superchain-registry/issues/806
- [x] https://github.com/ethereum-optimism/optimism/issues/13599
- [x] https://github.com/ethereum-optimism/optimism/issues/13994
- [x] https://github.com/ethereum-optimism/optimism/issues/14569

## Milestone: Post-Mainnet

Items which must be completed shortly after mainnet.

- [x] #14815
- [x] #13074
- [x] #13331
- [x] #13410
- [ ] #14055
- [ ] #13228
- [ ] #14235
- [ ] #14460

**Comment by K-Ho** [comment]
Sharing Product context on the importance of OPCM:


**Problem:**
There are two major pain points with upgrading the L1 contracts for the chains in the Superchain
1. Because many chains in the superchain currently have different versions of their L1 contracts, upgrading contracts requires a time consuming process of tracking every different version of the contracts for different chains and handling each upgrade differently.
If we do nothing, the contract changes for Isthmus would force us to perform the same time consuming manual tasks to track down all versions of the contracts and require more work to get all contracts to the same version.
2. If we keep adding chains to the SC with our upgrades process as-is, there is an enormous amount of increased manual labor for the OP Labs security team and for the Security Council. This includes manual validation of every storage slot, for every upgrade, for every chain—along with the ability to track any subtle variations that may exist for chains that are on different versions. This creates a lot of surface area for something to go wrong. 
**Solution**
1. OPCM upgrades will allow us to easily get all chains in the Superchain to the same version of the contracts with the Isthmus upgrade(although some chains *will* be permissioned vs. permissionless), making this version hell a thing of the past.
2. OPCM streamlines the security council signing process 

**Risks**
If we do not thoroughly test out the OPCM upgrade for Isthmus on devnets before the Isthmus testnet upgrade we could risk errors in the upgrade process.

**Comment by maurelian** [comment]
Closing this as the main project is complete. I will keep the sub tasks open for now to help guide maintenance work.
