### ISSUE TITLE
Jovian + Karst: Consensus influencing event nonces [TRACKER]

### ISSUE THREAD

**Issue by mdehoog** [ethereum-optimism/optimism#13543]
## Overview

This is a tracking issue for https://github.com/ethereum-optimism/specs/issues/330#issuecomment-2354217166, which introduces a nonce for L1 events that affect consensus (`SystemConfig.ConfigUpdate` and `OptimismPortal2.TransactionDeposited`).

Design doc PR: https://github.com/ethereum-optimism/design-docs/pull/182
Design review issue: https://github.com/ethereum-optimism/design-docs/issues/183

## Rollout plan

1. _Jovian_: introduce change in op-node / op-program / Kona to accept `ConfigUpdate` and `TransactionDeposited` for both version `0` and `1`. Version `1` will also contain an incrementing nonce in the upper 128-bits of the version argument. Also update the `L1Block` contract to track these nonces on the L2.
2. _Between Jovian + Karst_: roll out contract upgrades to `SystemConfig` and `OptimismPortal2` that introduce this new version `1` events with the nonce.
3. _Karst_: remove support for version `0` events, requiring incrementing nonces going forward. This guarantees that nonces are available, allowing for simplification of the derivation pipeline by supporting skipping L1 blocks that contain none of these events. 

## Step 1 TODOs (Jovian):
 - [ ] Specs: https://github.com/ethereum-optimism/specs/pull/487
 - [ ] Implementation:
     - [ ] https://github.com/ethereum-optimism/optimism/pull/13539
     - [ ] https://github.com/ethereum-optimism/op-geth/pull/457

## Step 2 TODOs (contract upgrades):
 - [ ] Devnet rollout
 - [ ] Testnet rollout
 - [ ] Mainnet rollout

## Step 3 TODOs (Karst):
 - [ ] Specs: WIP
 - [ ] Implementation: WIP

**Comment by mslipper** [comment]
Closing this out for now - I don't think we'll be implementing this for the time being. Will reopen if I receive guidance otherwise.
