### ISSUE TITLE
Calldata Cost Reduction Checklist

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#1841]
There have been some recent proposals to reduce the gas cost of calldata which would allow for rollups to be cheaper. The L1 portion of the fee (used to cover batch submission) is charged along with the L2 portion of the fee (used to cover L2 execution).

- https://github.com/ethereum/EIPs/pull/4488
- https://github.com/ethereum/EIPs/pull/4490

These changes would cause the `GasPriceOracle` predeploy to overcharge for the L1 gas price, since the calldata costs are hardcoded in the contract. This means that we need to upgrade the `GasPriceOracle` contract once this change goes into place. Currently, there is no proxy in front of the `GasPriceOracle` - perhaps the `GasPriceOracleV2` should be deployed behind a proxy so that it is upgradable. See [here](https://github.com/ethereum-optimism/optimism/blob/639e5b13f2ab94b7b49e1f8114ed05a064df8a27/packages/contracts/contracts/L2/predeploys/OVM_GasPriceOracle.sol#L150) for the implementation of how the L1 portion of the fee is currently computed.

In the meantime, the price discrepancy can be handled by setting the `scalar` or `overhead` values lower.
- https://github.com/ethereum-optimism/optimism/blob/639e5b13f2ab94b7b49e1f8114ed05a064df8a27/packages/contracts/contracts/L2/predeploys/OVM_GasPriceOracle.sol#L28
-  https://github.com/ethereum-optimism/optimism/blob/639e5b13f2ab94b7b49e1f8114ed05a064df8a27/packages/contracts/contracts/L2/predeploys/OVM_GasPriceOracle.sol#L30

TODOs:
- [ ]  Determine if using a proxy is the correct approach in the future
- [ ] Write the `GasPriceOracleV2` contract, which should be similar in functionality
- [ ] Hardfork/squash fork logic will be required to switch to the new `GasPriceOracleV2`
- [ ] Determine the correct values for the `scalar` and `overhead` to compensate for the cheaper calldata costs
