### ISSUE TITLE
feat(op-challenger): Verify Absolute Pre-state

### ISSUE THREAD

**Issue by refcell** [ethereum-optimism/optimism#6674]
**Description**

The `op-challenger` needs the absolute pre-state to attempt a "step" via its `Agent` component's `AttemptStep` method. In turn, the `Agent` queries it's composed `TraceProvider` for the absolute pre-state, implemented concretely by the cannon trace provider and the alphabet trace provider.

On startup (which is for now single-game spawned), the `op-challenger` should fetch the absolute pre-state from the on-chain  fault dispute game contract and compare this state with that of it's trace provider. If there is a mismatch, an error should be thrown.

### Tasks
- [x] Implement a `FetchAbsolutePrestate` method on the `Loader` component.
- [x] Unit test this new `FetchAbsolutePrestate` loader component method.
- [x] On service creation, validate the onchain absolute pre-state with the absolute pre-state from the local trace provider.

**Considered Alternatives**

Initially the thought was to pass the absolute-prestate in via a cli argument or "embed" this network-specific value in a mapping. But, since it is stored in the fault dispute game contract, it is much less error-prone and efficient to fetch this value from onchain.

**Tests**

Unit tests should be implemented for the `Loader` component.

**Linked Linear Ticket**

CLI-4286
