### ISSUE TITLE
feat(op-challenger): Load onchain Game Depth

### ISSUE THREAD

**Issue by refcell** [ethereum-optimism/optimism#6677]
**Description**

When playing a fault dispute game, the `op-challenger` needs to know the game depth for trace index and other game state calculations. Currently, this value is passed into the challenger via a CLI Flag `--game-depth`.

Instead of manually providing this game depth, the challenger should fetch the game depth via the `Loader` fault component on initialization and bubble up the error on failure.

Since the game depth is required for the initialization of the `Agent` fault component, it should be retrieved prior within the service component initialization.

### Tasks
- [ ] Implement a `FetchGameDepth` method on the `Loader` component.
- [ ] Unit test the new `FetchGameDepth` loader component method.
- [ ] On service init, fetch the game depth from the loader and pass this through to the Agent creation.

**Tests**

Unit tests implemented for the `Loader` component.

**Associated Linear Ticket**

CLI-4330
