### ISSUE TITLE
Update go-libp2p components

### ISSUE THREAD

**Issue by sebastianst** [ethereum-optimism/optimism#6699]
### Context 

As a follow-up to https://github.com/ethereum-optimism/optimism/pull/6032, where `go-libp2p-pubsub` got updated to fix a possible panic, we identified that multiple go-libp2p components can be updated. This enables us to benefit from the latest improvements and bug fixes of go-libp2p.

### Tasks

- [ ] Identify go-libp2p packages that can be updated. 
- [ ] Update them and adapt all usage to possible API changes or new functionality.
- [ ] Possibly adapt tests or add new ones if appropriate.

Note that we haven't recently updated go-libp2p packages, so whether this is trivial or involves some unforeseen lift is not known and finding this out is part of this issue.

The issue is done if all go-libp2p dependencies got updated and all existing usage has been updated and correct functioning of all dependent components has been confirmed.

### Metadata

* Contact: @ajsutton 
* Closes CLI-4119

**Comment by kagzgenius** [comment]
Hi I'd like to work on this.

**Comment by sebastianst** [comment]
@kagzgenius awesome, thanks for your interest! Are there any open questions or concerns before you can start?
cc @ajsutton

**Comment by kagzgenius** [comment]
Since this is my first contribution, getting a checklist of things to cover or areas of the code base to check for and an example of a git diff of what is expected to resolve this issue. These would be helpful to me as a new contributor. Thank you for the opportunity to contribute.

**Comment by tynes** [comment]
Hi @kagzgenius thank you for being interested in contributing. An example of a git diff would basically be implementing it ourselves :P You can look at the `go.mod` to see the libp2p related deps and try building the codebase with updated versions. There are `go mod` commands that are handy for updating packages. There will be compilation errors as the API has changed and you will need to fix them

**Comment by kagzgenius** [comment]
Ok thanks I will reach out if I run into any problems. 👍

**Comment by sebastianst** [comment]
@kagzgenius do you still want to work on this?

**Comment by kagzgenius** [comment]
Yes, I would still like to work on this issue.

**Comment by joohhnnn** [comment]
solved by [PR](https://github.com/ethereum-optimism/optimism/pull/7333), PLZ close this issue

**Comment by sebastianst** [comment]
@protolambda can you confirm that https://github.com/ethereum-optimism/optimism/pull/7333 updated all components that are in scope for this issue?

**Comment by protolambda** [comment]
@sebastianst I believe we are on the latest version of go-libp2p-pubsub, and libp2p just had a release 2 hours ago, but we're up-to-date with the latest before that, and the new release doesn't appear to fix/change any relevant code-paths (most WebRTC changes and some QUIC updates), so I'm ok with staying on the current releases.

**Comment by sebastianst** [comment]
Thanks for confirming!
