### ISSUE TITLE
[Tracking] Canyon Network Upgrade

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/optimism#7452]
This is the high level tracking issue for the canyon upgrade.

- [x] op-node config & override https://github.com/ethereum-optimism/optimism/pull/7215
- [x] op-geth config & override https://github.com/ethereum-optimism/op-geth/pull/133
- [x] https://github.com/ethereum-optimism/optimism/issues/6728
- [x] https://github.com/ethereum-optimism/op-geth/issues/143
- [x] https://github.com/ethereum-optimism/optimism/issues/7453
- [x] https://github.com/ethereum-optimism/op-geth/issues/144
- [x] Create2Deployer on base https://github.com/ethereum-optimism/op-geth/pull/126
- [x] https://github.com/ethereum-optimism/optimism/issues/7731
- [x] https://github.com/ethereum-optimism/client-pod/issues/164

**Comment by mslipper** [comment]
Closing as complete! Excellent work.
