### ISSUE TITLE
Ecotone: Cancun/Dencun support tracker

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#8701]
Specs draft: https://github.com/ethereum-optimism/optimism/pull/8602

- Cancun (Execution Layer):
    - [EIP-1153: Transient storage opcodes](https://eips.ethereum.org/EIPS/eip-1153)
    - [EIP-4844: Shard Blob Transactions](https://eips.ethereum.org/EIPS/eip-4844)
        - Blob transactions are disabled
    - [EIP-4788: Beacon block root in the EVM](https://eips.ethereum.org/EIPS/eip-4788)
        - The L1 beacon block root is embedded into L2
        - The Beacon roots contract deployment is automated
    - [EIP-5656: MCOPY - Memory copying instruction](https://eips.ethereum.org/EIPS/eip-5656)
    - [EIP-6780: SELFDESTRUCT only in same transaction](https://eips.ethereum.org/EIPS/eip-6780)
    - [EIP-7516: BLOBBASEFEE opcode](https://eips.ethereum.org/EIPS/eip-7516)
- Deneb (Consensus Layer): *not applicable to L2*
    - [EIP-7044: Perpetually Valid Signed Voluntary Exits](https://eips.ethereum.org/EIPS/eip-7044)
    - [EIP-7045: Increase Max Attestation Inclusion Slot](https://eips.ethereum.org/EIPS/eip-7045)
    - [EIP-7514: Add Max Epoch Churn Limit](https://eips.ethereum.org/EIPS/eip-7514)

superchain-registry:
- [x] Rename Eclipse to Ecotone https://github.com/ethereum-optimism/superchain-registry/pull/47
 
op-geth: https://github.com/ethereum-optimism/op-geth/pull/205
- [x] pull in superchain-registry change
- [x] Activate Cancun when Optimism Ecotone is active
- Blob transactions are disabled
  - [x] Tx-pool:
    - Disable entire blob sub-tx-pool here in [`eth/backend`](https://github.com/ethereum-optimism/op-geth/blob/25fd986a27b206b8454b2e9ceb4b699a238974ed/eth/backend.go#L256)
    - Update [`txpool.ValidateTransaction`](https://github.com/ethereum-optimism/op-geth/blob/dbe93022ea25f509b7253a166fcdd0b4037f5017/core/txpool/validation.go#L65),
      it's used by sub-pools to validate, and we already disabled the sub-pool, but better safe than sorry, in case the legacy-pool is misused.
  - [x] RPC:
    - Optimize happy-path by dropping tx, before processing in tx-pool,
      in [`SendTx`](https://github.com/ethereum-optimism/op-geth/blob/dbe93022ea25f509b7253a166fcdd0b4037f5017/eth/api_backend.go#L295),
      return `core.ErrTxTypeNotSupported`
  - [x] State-transition
    - `StateProcessor.Process` creates a signer based on the current block number with [`types.MakeSigner`],
      in case optimism config is active, we should return the london-signer.
    - `LatestSigner` is used by a bunch of utils. We should return the london-signer if optimism config is active.

TODO: we can consider refactoring the signer to implement an `OpStackSigner` that wraps the upstream signers and adds the diff of enabling deposits and disabling blob txs.

Monorepo: https://github.com/ethereum-optimism/optimism/pull/8707
- [x] pull in superchain-registry change (`go.mod` update)
- [x] pull in op-geth changes (`go.mod` update)
- [x] Rename Eclipse to Ecotone
- [x] Deploy-config change for Ecotone activation
- [x] Implement op-node attributes change to insert the exact specified beacon-block roots upgrade tx
- [x] Implement op-node attributes change to insert the beacon-block-root
- [x] Action test for beacon-block roots upgrade tx
- [x] Implement op-node attributes change to add new header beacon-block-root field
    - [x] Engine API v3 methods support 
    - [x] Update gossip execution block payload
- [x] Update specs etc. to refer to Ecotone, not Eclipse
   - [x] Also the hashes in the upgrade txn will need changing
- [x] Extend op-chain-ops L2 genesis to embed the beacon-block-root contract at the right address, if Cancun is active.

Code to embed in genesis:
```
cast code --rpc-url=https://ethereum-goerli-rpc.allthatnode.com/ 0x000F3df6D732807Ef1319fB7B8bB8522d0Beac02
0x3373fffffffffffffffffffffffffffffffffffffffe14604d57602036146024575f5ffd5b5f35801560495762001fff810690815414603c575f5ffd5b62001fff01545f5260205ff35b5f5ffd5b62001fff42064281555f359062001fff015500
```
Based on the deterministic code deployment of the EIP, the above should be the correct bytecode, for the `0x000F3df6D732807Ef1319fB7B8bB8522d0Beac02` that's in the EIP.

More TODOs, as discovered during implementation by @danyalprout (tracking now at https://github.com/ethereum-optimism/protocol-quest/issues/71)
- Modify op-ha to migrate to the new admin API
- Investigate whether to migrate op-wheel to V3 engine APIs
- Add some more tests for Ecotone specific blocks (parent beacon block root != nil)

**Comment by EvanJRichard** [comment]
- [x] Implement op-node attributes change to insert the exact specified beacon-block roots upgrade tx
I think this is [here](https://github.com/ethereum-optimism/optimism/pull/8707/files#diff-db79dd7a9ff2a2ef38e8eb19d6047e7f56f126deac3a2263a659dd2cdee55bf5R102-R109), checking off in main list
- [x] Implement op-node attributes change to insert the beacon-block-root
I think this is [here](https://github.com/ethereum-optimism/optimism/pull/8707/files#diff-db79dd7a9ff2a2ef38e8eb19d6047e7f56f126deac3a2263a659dd2cdee55bf5R133), checking off in main list
- [x] Action test for beacon-block roots upgrade tx
see `dencun_fork_test` and `ecotone_fork_test` in #8707 , checking off in main list
- [x] Implement op-node attributes change to add new header beacon-block-root field
    - [x] Check if Forkchoice update v3 is used
Poking around, some places in the `op-node` seem to use v2 and v3, and it's a little unclear to me which places need swapping. Leaving unchecked for now.
    - [x] Check if SSZ encoding needs update
 I've looked at the encoding in `op-service/eth/ssz.go`, and it looks to me like nothing needs updating, but I'm suspicious I'm wrong: it's surprising to me that the ssz wouldn't need changing. Leaving unchecked for now.

**Comment by sebastianst** [comment]
Tracking remaining work in separate tickets.
